apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: easyshop-ns
  name: redis-deploy
  labels:
    app: redisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: redis:7-alpine
        ports:
        - containerPort:  6379
